### ISSUE TITLE
[Docs] resources handle

### ISSUE THREAD

**Issue by DefTruth** [DefTruth/Awesome-LLM-Inference#1]
<img width="1788" alt="LLMs-Open-Papers-as-Book-v0 1_For_Beginners" src="https://github.com/DefTruth/LLMs-Open-Papers-as-Book/assets/31974251/03fac365-87da-4c9d-909c-ea2fe457b127">

**Comment by DefTruth** [comment]
<img width="1440" alt="v0 2" src="https://github.com/DefTruth/LLMs-Inference-Papers/assets/31974251/bb136842-8054-4599-8bfe-36c36f0e997f">

**Comment by DefTruth** [comment]
![image](https://github.com/DefTruth/Awesome-LLM-Inference/assets/31974251/ed16dc2e-08a4-4225-9a8c-ea6402e26fb8)

**Comment by DefTruth** [comment]
![image](https://github.com/DefTruth/Awesome-LLM-Inference/assets/31974251/b30f27db-3b65-4dce-92d0-0a94296095d7)
![image](https://github.com/DefTruth/Awesome-LLM-Inference/assets/31974251/c6b1b023-a52f-453e-95da-2041d10d3ebf)

**Comment by DefTruth** [comment]
![image](https://github.com/DefTruth/Awesome-LLM-Inference/assets/31974251/a0bab25e-58de-4248-85a2-8942be0ce370)

**Comment by DefTruth** [comment]
![image](https://github.com/DefTruth/Awesome-LLM-Inference/assets/31974251/0ed77e9d-a1eb-4095-9a82-bad624964e55)

**Comment by 2213601279** [comment]
非常感谢大佬慷慨的整理。【🥇】
这里增加一个XODO的软件手机、PC两不误
![image](https://github.com/DefTruth/Awesome-LLM-Inference/assets/45991092/540d58cb-597e-4f40-8163-1114c4bd5d36)

**Comment by DefTruth** [comment]
![llm-inference](https://github.com/DefTruth/Awesome-LLM-Inference/assets/31974251/75369339-1ed8-4474-ab33-a087d51b2872)

**Comment by DefTruth** [comment]
![image](https://github.com/DefTruth/Awesome-LLM-Inference/assets/31974251/4d9ab775-f200-471d-a289-e2b14296b633)

**Comment by DefTruth** [comment]
![LLM-Inference](https://github.com/DefTruth/Awesome-LLM-Inference/assets/31974251/29f8f014-7611-4108-93ce-beb67a1ed506)

**Comment by DefTruth** [comment]
![LLM Inference](https://github.com/DefTruth/Awesome-LLM-Inference/assets/31974251/358e897b-3af7-4913-9006-9f17b1d7e2cb)

**Comment by DefTruth** [comment]
![image](https://github.com/user-attachments/assets/494991a1-9096-414b-9d1c-dde0d5debcdf)

**Comment by DefTruth** [comment]
![diffusion-2](https://github.com/user-attachments/assets/decc861e-fe77-4eb7-aacf-7d27b6430e54)
![diffusion](https://github.com/user-attachments/assets/556b58d6-b78e-4d6b-97e0-84b992c52f1e)
![llm](https://github.com/user-attachments/assets/f47a5bb2-3889-4f94-89e9-61ebe899fe03)
