### ISSUE TITLE
Context compression methods?

### ISSUE THREAD

**Issue by liyucheng09** [DefTruth/Awesome-LLM-Inference#4]
This is such a great collection! Best llm reading list I came across.

I think it would be a good idea to add context compression methods such as [LlmLingua](https://github.com/microsoft/LLMLingua), [selective-context](https://github.com/liyucheng09/Selective_Context), and [auto-compressor](https://arxiv.org/abs/2305.14788).

**Comment by DefTruth** [comment]
would you like to submit a PR to add these two paper in this repo?

**Comment by liyucheng09** [comment]
merged #7
