### ISSUE TITLE
add code link【ABQ-LLM 】

### ISSUE THREAD

**Issue by lswzjuer** [DefTruth/Awesome-LLM-Inference#45]
Hello, I am the author of ABQ-LLM. Our code has been open sourced. We want more people to see this work. We hope you can add a code link.   https://github.com/bytedance/ABQ-LLM

**Comment by DefTruth** [comment]
@lswzjuer hi~ feel free to submit a PR to add it into this repo, i will review and merge it

**Comment by DefTruth** [comment]
done
