### ISSUE TITLE
New papers: KV Compression/Quant

### ISSUE THREAD

**Issue by liyucheng09** [DefTruth/Awesome-LLM-Inference#5]
Just came across some nice papers about KV compress/quant. Let me know if you feel useful to include them in the readling list.

[no token left behind](https://arxiv.org/pdf/2402.18096.pdf).

[get more with less](https://arxiv.org/pdf/2402.09398.pdf).

**Comment by DefTruth** [comment]
LGTM

**Comment by DefTruth** [comment]
@liyucheng09 would you like to submit a PR to add these two paper in this repo?

**Comment by liyucheng09** [comment]
#7 merged
